# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CandyMessanger' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CandyMessanger
  
  # FireBase
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  
  # Animation
  pod 'lottie-ios'

  target 'CandyMessangerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CandyMessangerUITests' do
    # Pods for testing
  end

end
